version: '3.6'

services:
  ravencoin:
    restart: always
    image: realnuts/docker_ravend:4.2.1
    ports:
      - "8766:8766"
      - "8767:8767"
    volumes:
      - /opt/blockchain_data/raven_data:/home/raven/.raven/
      - ./config/mainnet.conf:/home/raven/.raven/raven.conf
